### ISSUE TITLE
ImportError: No module named notebooks.filenbmanager

### ISSUE THREAD

**Issue by samdeeplearning** [robchambers/nbserve#29]
All I've done:
`$pip install nbserve`
`$nbserve`
`Traceback (most recent call last):`
`  File "/Users/samuelputnam/anaconda/bin/nbserve", line 7, in <module>`
`    from nbserve.cli import main`
`  File "/Users/samuelputnam/anaconda/lib/python2.7/site-packages/nbserve/__init__.py", line 2, in <module>`
`    from .app import flask_app, set_config, update_config`
`  File "/Users/samuelputnam/anaconda/lib/python2.7/site-packages/nbserve/app.py", line 10, in <module>`
`    from IPython.html.services.notebooks.filenbmanager import FileNotebookManager`
`ImportError: No module named notebooks.filenbmanager`
Per: http://stackoverflow.com/questions/31397421/ipython-server-cant-launch-no-module-named-notebook-notebookapp (a similar, but different question)
`pip install jupyter`
`pip uninstall -y IPython`
`pip install ipython==3.2.1`
Same output.
Do you think I might be missing something Flask-related or specific to nbserve?

**Comment by robchambers** [comment]
Ah, this is just because the software hasn't been updated in a couple of years, and IPython / Jupyter have changed a lot in that time. I think I almost have it working; I will post here if I manage to get it going again.

**Comment by robchambers** [comment]
@samdeeplearning , I think that I've got everything all fixed up. Would you mind testing? The newest version on PIP should work fine, if you just repeat the commands you ran before...

Would love to hear any feedback.

Cheers,
Rob

**Comment by SamPutnam** [comment]
`pip uninstall nbserve`
`pip install nbserve`
`nbserve`
Running. For usage info and options, type nbserve -h.
Press Ctrl-C or similar to stop.
Runner is ready.
✔️️
